### ISSUE TITLE
PDS name with . (dot) being re-written with _ (underscore)

### ISSUE THREAD

**Issue by dremio-brock** [rymurr/dremio_graph#1]
version: 
python version: 3.7
OS version: windows 10

When getting pds' with . (dot) in the name, it appears to be getting replacing the . with an _ (underscore). In the case below it should be ``CUST_INDUSTRY_SUPP_VW.csv`` instead of ``CUST_INDUSTRY_SUPP_VW_csv``

```
Traceback (most recent call last):
  File "dremio_graph\dremio_graph\fetch.py", line 91, in read_pds
    item = sub_catalog.get()[pds['TABLE_NAME'].replace('.', '_').replace('-', '_').replace(' ', '_')]
KeyError: 'CUST_INDUSTRY_SUPP_VW_csv'
```

**Comment by rymurr** [comment]
should be fixed, pull and try again?
